# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8 --append-config=setup.cfg
        language: system
        types: [file, python]

    -   id: pylint
        name: pylint
        entry: pylint --rcfile=pylintrc
        language: system
        types: [file, python]
